### ISSUE TITLE
`get_data`: broken merge with bmf for some core files

### ISSUE THREAD

**Issue by chickymonkeys** [UrbanInstitute/nccsdata#15]
Hi there, 

I am loading some of the core data in bulk with the package to check a couple of things, and I just wanted let you know that some core files fail to merge with the BMF using `append.bmf = TRUE`.

For example, the following code

```r
core2005 <- nccsdata::get_data(dsname = "core", time = "2005",  append.bmf = TRUE)
```

Gives: 

```
Error: Incompatible join types: x.EIN (double) and i.EIN (character)
```

I think this is because there are some parsing issues in a few of the core data ex ante (I have those in the legacy files as well). At some point, probably the files were saved with the EIN as integers losing all the leading zeroes. I am usually using a function to parse EINs when I open the files just to be sure that they match, filling the leading zeroes in case EIN, once parsed as character if it was not, has 9-digits.

Hope it helps!

Best,
Alessandro

**Comment by Thiyaghessan** [comment]
Hi Alessandro,

Thank you for this! I will work on resolving this bug this week and will get back to you once it's done!

**Comment by chickymonkeys** [comment]
Hi Thiya, now it works. Thanks!

**Comment by happygoboohoo** [comment]
HI Thiyaghessan,
I think the issue persists. I found this thread after striking out with solutions similar to the snippet below. My R skills are limited, but I'm hoping that resolving in R will be a little cleaner than exporting/joining in postgres.
 
`corebmf <- get_data(dsname = "core",
                    time = "1989",
                    append.bmf = TRUE,
                    convert.columns = list(EIN = "character"))`
                   
Thanks in advance!

**Comment by Thiyaghessan** [comment]
Hi @happygoboohoo could you attach a screenshot of the code and the error message received? Thank you!

**Comment by happygoboohoo** [comment]
`library(nccsdata)`

`corebmf1989 <- get_data(dsname = "core",
                         time = "1989",
                         append.bmf = TRUE)`

> Valid inputs detected. Retrieving data.
Downloading core data
Requested files have a total size of 280.2 MB. Proceed
                      with download? Enter Y/N (Yes/no/cancel) Y
 [100%] Downloaded 90191822 bytes...
|--------------------------------------------------|
|==================================================|
Core data downloaded
Downloading bmf data
trying URL 'https://nccsdata.s3.us-east-1.amazonaws.com/current/bmf/bmf-master.rds'
Content type 'application/octet-stream' length 195379382 bytes (186.3 MB)
==================================================
downloaded 186.3 MB

> bmf data downloaded. Appending bmf
Error in bmerge(i, x, leftcols, rightcols, roll, rollends, nomatch, mult,  : 
  Incompatible join types: x.EIN (character) and i.EIN (integer)
  
I went ahead and forced a reinstall just to make sure there were no SHA issues--no luck.
Thanks again,
-b

**Comment by Thiyaghessan** [comment]
Thank you. Our package is currently undergoing a code review. Once that process is concluded, I will investigate this bug.

**Comment by Thiyaghessan** [comment]
Hi @happygoboohoo the issue should be resolved now, let me know if it still persists!
